spring:
  jackson:
    serialization:
      write_dates_as_timestamps: false
  thymeleaf:
    cache: false
  resources:
    chain:
      cache: false
  datasource:
    url: jdbc:h2:file:./data/${screencaster.database}/notesv2;DB_CLOSE_ON_EXIT=FALSE
  jpa:
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
# we replace springs default multipart handling
      enabled: false
# but we still use the multipart configuration properties
      max-file-size: 64MB
  jmx:
    enabled: false

server:
  port: 9999
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,text/css,application/javascript,image/jpeg,image/png
  servlet:
    context-path:
  jetty:
    accesslog:
      enabled: true
      ignore-paths: ["/screenshot.jpg","/webjars/*","/css/*","/js/*"]


screencaster:
  refreshIntervalMillis: 250
  refreshPointerMillis: 150
  database: default
  grabbing:
    quality: 0.7
  fileStore:
    location: data
