spring:
  jackson:
    serialization:
      write_dates_as_timestamps: false
  thymeleaf:
    cache: false
  resources:
    chain:
      cache: false
  datasource:
    url: jdbc:h2:file:./data/${screencaster.database}/notes;DB_CLOSE_ON_EXIT=FALSE
  jpa:
    hibernate:
      ddl-auto: update
  http:
    multipart:
      max-file-size: 64MB
      file-size-threshold: 128KB

server:
  port: 9999
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,text/css,application/javascript,image/jpeg,image/png


screencaster:
  refreshIntervalMillis: 250
  refreshPointerMillis: 150
  database: default
  fileStore:
    location: data
