server:
  port: 9999
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,text/css,application/javascript,image/jpeg,image/png

spring:
  jackson:
    serialization:
      write_dates_as_timestamps: false
  thymeleaf:
    cache: false
  resources:
    chain:
      cache: false


screencaster:
  refreshIntervalMillis: 250
