spring:
  jackson:
    serialization:
      write_dates_as_timestamps: false
  thymeleaf:
    cache: false
  resources:
    chain:
      cache: false
  datasource:
    url: jdbc:h2:file:./data/${screencaster.database}/notes;DB_CLOSE_ON_EXIT=FALSE
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8443
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,text/css,application/javascript,image/jpeg,image/png

  ssl:
# $JAVA_HOME/bin/keytool -genkey -alias euler -keyalg RSA -keypass changeit -storepass changeit -keystore ./keystore.jks
    key-store: data/keystore.jks
    key-store-password: changeit
    key-password: changeit
    protocol: TLSv1.2

screencaster:
  refreshIntervalMillis: 250
  refreshPointerMillis: 150
  database: default
  fileStore:
    location: data
